# -*- coding: utf-8 -*-
"""correlation_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujhjmPQYZDKTteta-fWdS4F8yS3rokBm
"""

import pandas as pd
from .timestamp_alignment import align_timestamps
from .insight_generator import generate_insight


def correlate_low_engagement(
    vision_df: pd.DataFrame,
    nlp_df: pd.DataFrame,
    tolerance_seconds: int = 3,
) -> pd.DataFrame:
    """
    Correlates low engagement moments with NLP topics
    while handling edge cases and timestamp mismatches.
    """

    if vision_df is None or nlp_df is None:
        raise ValueError("Input data must not be None.")

    if vision_df.empty or nlp_df.empty:
        return pd.DataFrame(
            columns=[
                "timestamp",
                "topic",
                "engagement_level",
                "insight_text",
            ]
        )

    vision_df = vision_df.copy()
    nlp_df = nlp_df.copy()

    vision_df["timestamp"] = pd.to_datetime(
        vision_df["timestamp"], errors="coerce"
    )
    nlp_df["timestamp"] = pd.to_datetime(
        nlp_df["timestamp"], errors="coerce"
    )

    vision_df = vision_df.dropna(subset=["timestamp"])
    nlp_df = nlp_df.dropna(subset=["timestamp"])

    low_engagement = vision_df[
        vision_df["engagement_level"].str.lower() == "low"
    ]

    if low_engagement.empty:
        return pd.DataFrame(
            columns=[
                "timestamp",
                "topic",
                "engagement_level",
                "insight_text",
            ]
        )

    aligned = align_timestamps(
        low_engagement,
        nlp_df,
        tolerance_seconds,
    )

    aligned = aligned.dropna(subset=["current_topic"])

    aligned = aligned.rename(
        columns={"current_topic": "topic"}
    )

    aligned["insight_text"] = aligned.apply(
        generate_insight,
        axis=1,
    )

    result = aligned[
        ["timestamp", "topic", "engagement_level", "insight_text"]
    ]

    result = result.drop_duplicates(
        subset=["timestamp", "topic"]
    )

    return result.reset_index(drop=True)