# -*- coding: utf-8 -*-
"""db_reader. ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujhjmPQYZDKTteta-fWdS4F8yS3rokBm
"""

import pandas as pd
import sqlite3


def read_vision_data(db_path: str) -> pd.DataFrame:
    conn = sqlite3.connect(db_path)

    query = """
    SELECT
        timestamp,
        face_detected,
        engagement_level,
        emotion
    FROM vision_data
    """

    df = pd.read_sql(query, conn)
    conn.close()
    return df


def read_nlp_data(db_path: str) -> pd.DataFrame:
    conn = sqlite3.connect(db_path)

    query = """
    SELECT
        timestamp,
        current_topic,
        sentiment,
        keywords
    FROM nlp_data
    """

    df = pd.read_sql(query, conn)
    conn.close()
    return df