# -*- coding: utf-8 -*-
"""db_writer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujhjmPQYZDKTteta-fWdS4F8yS3rokBm
"""

import sqlite3
import pandas as pd


def save_insights(df: pd.DataFrame, db_path: str):

    conn = sqlite3.connect(db_path)

    conn.execute("""
    CREATE TABLE IF NOT EXISTS insights (
        timestamp TEXT,
        topic TEXT,
        engagement_level TEXT,
        insight_text TEXT,
        UNIQUE(timestamp, topic)
    )
    """)

    df.to_sql(
        "insights",
        conn,
        if_exists="append",
        index=False,
    )

    conn.commit()
    conn.close()