# -*- coding: utf-8 -*-
"""insight_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xeU36GoNilx6CU_GwfMAlPvKKy1xzuE9
"""

import pandas as pd


def generate_insight(row: pd.Series) -> str:
    return (
        f"Low engagement detected during topic "
        f"'{row['topic']}' with emotion "
        f"'{row['emotion']}'."
    )