# -*- coding: utf-8 -*-
"""insight_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujhjmPQYZDKTteta-fWdS4F8yS3rokBm
"""

import pandas as pd


def generate_insight(row: pd.Series) -> str:
    topic = row["topic"]
    emotion = row["emotion"]

    if emotion.lower() == "sad":
        return f"Students engagement dropped during {topic} explanation."
    elif emotion.lower() == "neutral":
        return f"Students showed reduced interaction while discussing {topic}."
    else:
        return f"Engagement decreased slightly during {topic} session."