# -*- coding: utf-8 -*-
"""mock_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujhjmPQYZDKTteta-fWdS4F8yS3rokBm
"""

import pandas as pd


def generate_mock_vision():
    return pd.DataFrame({
        "timestamp": pd.date_range(
            "2026-01-01 10:00:00",
            periods=10,
            freq="1min"
        ),
        "face_detected": [True] * 10,
        "engagement_level": [
            "High", "Low", "Low", "Medium", "Low",
            "High", "Medium", "Low", "High", "Low"
        ],
        "emotion": [
            "Happy", "Sad", "Neutral", "Happy", "Sad",
            "Happy", "Neutral", "Sad", "Happy", "Neutral"
        ],
    })


def generate_mock_nlp():
    return pd.DataFrame({
        "timestamp": pd.date_range(
            "2026-01-01 10:00:00",
            periods=10,
            freq="1min"
        ),
        "current_topic": [
            "AI", "ML", "DL", "CV", "Robotics",
            "NLP", "Data", "Vision", "Sensors", "Networks"
        ],
        "sentiment": ["Positive"] * 10,
        "keywords": ["k"] * 10,
    })