# -*- coding: utf-8 -*-
"""performance_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujhjmPQYZDKTteta-fWdS4F8yS3rokBm
"""

import time
from data.mock_data import generate_mock_vision, generate_mock_nlp
from correlation.correlation import correlate_low_engagement


def run_performance_test():

    vision_small = generate_mock_vision()
    nlp_small = generate_mock_nlp()

    start = time.perf_counter()
    correlate_low_engagement(vision_small, nlp_small)
    print("Small dataset time:", time.perf_counter() - start)

    vision_large = vision_small.loc[
        vision_small.index.repeat(1000)
    ].reset_index(drop=True)

    nlp_large = nlp_small.loc[
        nlp_small.index.repeat(1000)
    ].reset_index(drop=True)

    start = time.perf_counter()
    correlate_low_engagement(vision_large, nlp_large)
    print("Large dataset time:", time.perf_counter() - start)


if __name__ == "__main__":
    run_performance_test()