# -*- coding: utf-8 -*-
"""timestamp_alignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xeU36GoNilx6CU_GwfMAlPvKKy1xzuE9
"""

import pandas as pd


def align_timestamps(
    vision_df: pd.DataFrame,
    nlp_df: pd.DataFrame,
    tolerance_seconds: int = 30,
) -> pd.DataFrame:

    vision_df = vision_df.sort_values("timestamp")
    nlp_df = nlp_df.sort_values("timestamp")

    aligned = pd.merge_asof(
        vision_df,
        nlp_df,
        on="timestamp",
        direction="nearest",
        tolerance=pd.Timedelta(seconds=tolerance_seconds),
    )

    return aligned